#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubyboy'
require 'optparse'

begin
  OptionParser.new do |opts|
    opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} ROM_PATH"

    opts.on('-h', '--help', 'Displays this help') do
      puts opts
      exit
    end
  end.parse!
rescue OptionParser::ParseError => e
  puts e.message
  puts "Usage: #{File.basename($PROGRAM_NAME)} ROM_PATH"
  exit 1
end

rom_path = ARGV.shift || 'lib/roms/tobu.gb'

puts "Ruby: #{RUBY_VERSION}"
if defined?(RubyVM::YJIT)
  puts "YJIT: #{RubyVM::YJIT.enabled?}"
else
  puts 'YJIT is not available in this environment.'
end

Rubyboy::Emulator.new(rom_path).start
