#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubyboy'
require 'optparse'

frames = nil
realtime = true

begin
  OptionParser.new do |opts|
    opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} [ROM_PATH]"

    opts.on('--frames N', 'Exit after N frames (positive integer)') do |value|
      value = Integer(value)
      raise OptionParser::InvalidArgument, 'frames must be a positive integer' unless value > 0

      frames = value
    end
    opts.on('--unlimited', 'Disable real-time synchronization; excess audio is dropped') { realtime = false }

    opts.on('-h', '--help', 'Displays this help') do
      puts opts
      exit
    end
  end.parse!
rescue OptionParser::ParseError, ArgumentError => e
  puts e.message
  puts "Usage: #{File.basename($PROGRAM_NAME)} [ROM_PATH]"
  exit 1
end

rom_path = ARGV.shift || Rubyboy::Rom::DEFAULT_PATH

puts "Ruby: #{RUBY_VERSION}"
if defined?(RubyVM::YJIT)
  puts "YJIT: #{RubyVM::YJIT.enabled?}"
else
  puts 'YJIT is not available in this environment.'
end

Rubyboy::Emulator.new(rom_path).start(frames:, realtime:)
