#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bench'
require 'optparse'

options = {}
begin
  OptionParser.new do |opts|
    opts.banner = "Usage: #{File.basename($PROGRAM_NAME)} [options]"

    opts.on('--count COUNT', Integer, 'Number of trials for the benchmark') do |count|
      options[:count] = count
    end

    opts.on('--frames FRAMES', Integer, 'Number of measured frames per trial') do |frames|
      options[:frames] = frames
    end

    opts.on('--warmup-frames FRAMES', Integer, 'Number of unmeasured warmup frames per trial (default: 0)') do |frames|
      options[:warmup_frames] = frames
    end

    opts.on('--rom-path ROM_PATH', String, 'Path to the ROM file') do |rom_path|
      options[:rom_path] = rom_path
    end

    opts.on('-h', '--help', 'Displays this help') do
      puts opts
      exit
    end
  end.parse!
rescue OptionParser::ParseError, ArgumentError => e
  warn e.message
  warn "Usage: #{File.basename($PROGRAM_NAME)} --count NUM --frames NUM --rom-path FILEPATH"
  exit 1
end

puts "Ruby: #{RUBY_VERSION}"
if defined?(RubyVM::YJIT)
  puts "YJIT: #{RubyVM::YJIT.enabled?}"
else
  puts 'YJIT is not available in this environment.'
end

begin
  Rubyboy::Bench.new.run(**options)
rescue ArgumentError => e
  warn e.message
  exit 1
end
